### ISSUE TITLE
SIEVE running time on the example data

### ISSUE THREAD

**Issue by faridrashidi** [szczurek-lab/SIEVE#1]
Dear SIEVE developers,

I'm trying to run SIEVE on the provided example with 40 cells, 762 mutations and 4238 background sites but after 8 hours with 16 cores SIEVE is not able to produce any output. Would you kindly provide a test input of a smaller size that SIEVE can handle in a reasonable time?

Thank you

**Comment by senbaikang** [comment]
Hi Farid,

Thank you for trying out SIEVE. I have added a smaller example dataset with 10 cells, 273 candidate variant sites, and 9727 background sites under `examples/data/10_cells`. Let me know if you have further questions.

Best,
Senbai

**Comment by faridrashidi** [comment]
Hi Senbai,

Thank you for adding the smaller example dataset. I could successfully run SIEVE on it, although I had to remove all the type checking from `set_up_stage2_from_stage1.py` because it was giving me the following error:

```
Traceback (most recent call last):
  File "scripts/set_up_stage2_from_stage1.py", line 8, in <module>
    def get_parent2children_tag() -> dict[str, list[str]]:
TypeError: 'type' object is not subscriptable
```

One question, is the final inferred phylogenetic tree written in `results/stage2/phylogenetic_inference_dir/rmc_stage_1-rmc_stage_2/rmc_stage_1-rmc_stage_2.tree`? What format is it? How can I visualize it?

Thank you again

**Comment by senbaikang** [comment]
Hi Farid,

I am glad that it worked!

For the problem you encountered in `set_up_stage2_from_stage1.py`, may I ask the version of python you are using? This problem will be gone if you run the pipeline in docker or create a conda environment with `examples/environment.yml`.

For the inferred phylogenetic tree, you are right -- it is written in `results/stage2/phylogenetic_inference_dir/rmc_stage_1-rmc_stage_2/rmc_stage_1-rmc_stage_2.tree` with all the details. A simpler version is written in `results/stage2/phylogenetic_inference_dir/rmc_stage_1-rmc_stage_2/rmc_stage_1-rmc_stage_2_simple.tree`, only containing the tree structure and branch lengths. Both of them are of `NEXUS` format, which can be visualized using, e.g., [figtree](http://tree.bio.ed.ac.uk/software/figtree) and [iTOL](https://itol.embl.de).

Hope this helps.

Best,
Senbai

**Comment by faridrashidi** [comment]
I appreciate you, Senbai. It was quite useful. I used Snakemake pipeline with Python 3.8.10.
I'm having trouble utilizing DataFilter to create SIEVE input for real data that we have; if you could look at the related issues on the DataFilter project, that would be greatly appreciated.
Thank you very much.
